// نظام أشكال (Skins) لماسكوت المساعد.
// كل شكل صورة 3D + سعر بالكريدت + مميزات (perks): كريدت يومي مجاني، خصم على التلخيص/التوليد، وحركات حصرية.
// كل ما الشكل أغلى كل ما مميزاته أقوى.

const ROBOT_MODEL_URL = "/models/robot-expressive.glb";
const ROBOT_ACTIONS = {
  idle: ["Idle", "Standing"],
  active: ["Dance", "Walking", "Running"],
  talking: ["Dance", "Idle"],
};

const MONSTER_BIPED_ACTIONS = {
  idle: ["CharacterArmature|Idle"],
  active: ["CharacterArmature|Dance", "CharacterArmature|Walk", "CharacterArmature|Jump", "CharacterArmature|Bite_Front"],
  talking: ["CharacterArmature|Yes", "CharacterArmature|Dance", "CharacterArmature|Idle"],
};

const MONSTER_COMBAT_ACTIONS = {
  idle: ["CharacterArmature|Idle"],
  active: ["CharacterArmature|Run", "CharacterArmature|Punch", "CharacterArmature|Walk", "CharacterArmature|Jump"],
  talking: ["CharacterArmature|Wave", "CharacterArmature|Yes", "CharacterArmature|Punch", "CharacterArmature|Idle"],
};

const MONSTER_FLYING_ACTIONS = {
  idle: ["CharacterArmature|Flying_Idle"],
  active: ["CharacterArmature|Fast_Flying", "CharacterArmature|Headbutt", "CharacterArmature|Punch"],
  talking: ["CharacterArmature|Yes", "CharacterArmature|Headbutt", "CharacterArmature|Flying_Idle"],
};

const monsterModel = (slug, title, actions, options = {}) => ({
  name: title,
  url: `/models/poly-monsters/${slug}.glb`,
  poster: `/mascots/poly-monsters/${slug}.webp`,
  licenseId: `poly-${slug}`,
  fitSize: 2.45,
  cameraY: 0.12,
  cameraZ: 5.1,
  autoRotateSpeed: 0.0028,
  actions,
  ...options,
});

const POLY_MONSTER_SKINS = [
  {
    id: "dragon_whelp",
    name: "Dragon Whelp",
    emoji: "🐉",
    img: "/mascots/poly-monsters/dragon.webp",
    tier: "legendary",
    price: 620,
    glow: "#ff6b1a",
    motion: "inferno",
    model3d: monsterModel("dragon", "Dragon Whelp", MONSTER_FLYING_ACTIONS, {
      fitSize: 2.9,
      cameraY: 0.05,
      cameraZ: 4.8,
      autoRotateSpeed: 0.0024,
    }),
    dailyCredits: 5,
    discountPct: 17,
    desc: "Real animated 3D dragon with flying, headbutt and combat actions.",
    perks: ["5 كريدت كل يوم", "خصم 17% على التلخيص", "Flying + combat GLB actions"],
  },
  {
    id: "ancient_dragon",
    name: "Ancient Dragon",
    emoji: "🔥",
    img: "/mascots/poly-monsters/dragon-evolved.webp",
    tier: "mythic",
    price: 1050,
    glow: "#f97316",
    motion: "ascend",
    model3d: monsterModel("dragon-evolved", "Ancient Dragon", MONSTER_FLYING_ACTIONS, {
      fitSize: 2.95,
      cameraY: 0.05,
      cameraZ: 4.75,
      autoRotateSpeed: 0.0022,
    }),
    dailyCredits: 9,
    discountPct: 24,
    desc: "Large evolved dragon with stronger wings, flight idle and attack motion.",
    perks: ["9 كريدت كل يوم", "خصم 24% على التلخيص", "Evolved dragon GLB"],
  },
  {
    id: "red_demon",
    name: "Red Demon",
    emoji: "😈",
    img: "/mascots/poly-monsters/demon.webp",
    tier: "legendary",
    price: 680,
    glow: "#ef4444",
    motion: "inferno",
    model3d: monsterModel("demon", "Red Demon", MONSTER_FLYING_ACTIONS, {
      fitSize: 2.62,
      cameraY: 0.08,
      cameraZ: 4.95,
      autoRotateSpeed: 0.003,
    }),
    dailyCredits: 6,
    discountPct: 19,
    desc: "Winged demon with flying idle, punch and headbutt animations.",
    perks: ["6 كريدت كل يوم", "خصم 19% على التلخيص", "Winged demon actions"],
  },
  {
    id: "blue_demon",
    name: "Blue Demon",
    emoji: "💠",
    img: "/mascots/poly-monsters/blue-demon.webp",
    tier: "legendary",
    price: 720,
    glow: "#22d3ee",
    motion: "scan",
    model3d: monsterModel("blue-demon", "Blue Demon", MONSTER_COMBAT_ACTIONS, {
      fitSize: 2.5,
      cameraY: 0.16,
      cameraZ: 5.15,
      autoRotateSpeed: 0.0032,
    }),
    dailyCredits: 6,
    discountPct: 20,
    desc: "Tall blue combat demon with run, punch, wave and weapon actions.",
    perks: ["6 كريدت كل يوم", "خصم 20% على التلخيص", "Combat-ready GLB"],
  },
  {
    id: "orc_guard",
    name: "Orc Guard",
    emoji: "🛡️",
    img: "/mascots/poly-monsters/orc-enemy.webp",
    tier: "epic",
    price: 430,
    glow: "#84cc16",
    motion: "mech",
    model3d: monsterModel("orc-enemy", "Orc Guard", MONSTER_BIPED_ACTIONS, {
      fitSize: 2.35,
      cameraY: 0.12,
      cameraZ: 5.15,
    }),
    dailyCredits: 3,
    discountPct: 12,
    desc: "Animated orc enemy with dance, walk, jump and bite actions.",
    perks: ["3 كريدت كل يوم", "خصم 12% على التلخيص", "Orc battle actions"],
  },
  {
    id: "frost_yeti",
    name: "Frost Yeti",
    emoji: "❄️",
    img: "/mascots/poly-monsters/yeti.webp",
    tier: "epic",
    price: 520,
    glow: "#93c5fd",
    motion: "cosmic",
    model3d: monsterModel("yeti", "Frost Yeti", MONSTER_BIPED_ACTIONS, {
      fitSize: 2.4,
      cameraY: 0.12,
      cameraZ: 5.05,
    }),
    dailyCredits: 4,
    discountPct: 14,
    desc: "Heavy frost creature with idle, dance, jump and walk animations.",
    perks: ["4 كريدت كل يوم", "خصم 14% على التلخيص", "Yeti motion set"],
  },
  {
    id: "arcane_wizard",
    name: "Arcane Wizard",
    emoji: "🪄",
    img: "/mascots/poly-monsters/wizard.webp",
    tier: "epic",
    price: 460,
    glow: "#c084fc",
    motion: "arcane",
    model3d: monsterModel("wizard", "Arcane Wizard", MONSTER_BIPED_ACTIONS, {
      fitSize: 2.3,
      cameraY: 0.14,
      cameraZ: 5.05,
    }),
    dailyCredits: 3,
    discountPct: 13,
    desc: "Animated wizard mascot for study magic and focused review.",
    perks: ["3 كريدت كل يوم", "خصم 13% على التلخيص", "Wizard GLB actions"],
  },
  {
    id: "shadow_ninja",
    name: "Shadow Ninja",
    emoji: "🥷",
    img: "/mascots/poly-monsters/ninja.webp",
    tier: "rare",
    price: 340,
    glow: "#818cf8",
    motion: "scan",
    model3d: monsterModel("ninja", "Shadow Ninja", MONSTER_BIPED_ACTIONS, {
      fitSize: 2.28,
      cameraY: 0.14,
      cameraZ: 5.0,
    }),
    dailyCredits: 2,
    discountPct: 9,
    desc: "Fast ninja mascot with walk, jump, dance and response actions.",
    perks: ["2 كريدت كل يوم", "خصم 9% على التلخيص", "Ninja action set"],
  },
  {
    id: "cosmic_alien",
    name: "Cosmic Alien",
    emoji: "👽",
    img: "/mascots/poly-monsters/alien.webp",
    tier: "epic",
    price: 410,
    glow: "#34d399",
    motion: "cosmic",
    model3d: monsterModel("alien", "Cosmic Alien", MONSTER_BIPED_ACTIONS, {
      fitSize: 2.34,
      cameraY: 0.12,
      cameraZ: 5.05,
    }),
    dailyCredits: 3,
    discountPct: 12,
    desc: "Alien study creature with dance, yes/no, walk and jump actions.",
    perks: ["3 كريدت كل يوم", "خصم 12% على التلخيص", "Alien animated GLB"],
  },
  {
    id: "void_ghost",
    name: "Void Ghost",
    emoji: "👻",
    img: "/mascots/poly-monsters/ghost.webp",
    tier: "rare",
    price: 360,
    glow: "#a78bfa",
    motion: "float",
    model3d: monsterModel("ghost", "Void Ghost", MONSTER_FLYING_ACTIONS, {
      fitSize: 2.55,
      cameraY: 0.08,
      cameraZ: 4.95,
      autoRotateSpeed: 0.003,
    }),
    dailyCredits: 2,
    discountPct: 10,
    desc: "Floating ghost with flying idle, fast flying and attack animations.",
    perks: ["2 كريدت كل يوم", "خصم 10% على التلخيص", "Floating GLB actions"],
  },
  {
    id: "skull_ghost",
    name: "Skull Ghost",
    emoji: "💀",
    img: "/mascots/poly-monsters/ghost-skull.webp",
    tier: "legendary",
    price: 640,
    glow: "#e5e7eb",
    motion: "pulse",
    model3d: monsterModel("ghost-skull", "Skull Ghost", MONSTER_FLYING_ACTIONS, {
      fitSize: 2.58,
      cameraY: 0.08,
      cameraZ: 4.95,
      autoRotateSpeed: 0.003,
    }),
    dailyCredits: 5,
    discountPct: 17,
    desc: "Skull ghost with flight, hit reaction, punch and headbutt animations.",
    perks: ["5 كريدت كل يوم", "خصم 17% على التلخيص", "Skull ghost action rig"],
  },
  {
    id: "dino_runner",
    name: "Dino Runner",
    emoji: "🦖",
    img: "/mascots/poly-monsters/dino.webp",
    tier: "epic",
    price: 490,
    glow: "#fb923c",
    motion: "bounce",
    model3d: monsterModel("dino", "Dino Runner", MONSTER_COMBAT_ACTIONS, {
      fitSize: 2.5,
      cameraY: 0.15,
      cameraZ: 5.15,
      autoRotateSpeed: 0.0031,
    }),
    dailyCredits: 4,
    discountPct: 14,
    desc: "Animated dino with idle, run, punch, weapon, jump and wave actions.",
    perks: ["4 كريدت كل يوم", "خصم 14% على التلخيص", "Dino action rig"],
  },
];

export const MASCOT_SKINS = [
  {
    id: "default",
    name: "Black Fighters Guide",
    emoji: "🎓",
    img: "https://media.base44.com/images/public/6a2aa7216a5767b90e98bdea/c838c9aef_generated_image.png",
    tier: "free",
    price: 0,
    glow: "#00e5ff",
    motion: "float",
    dailyCredits: 0,
    discountPct: 0,
    desc: "الشكل الأساسي المجاني — يبدأ معاك من اليوم الأول.",
    perks: ["متاح للجميع", "حركة طفو بسيطة"],
  },
  ...POLY_MONSTER_SKINS,
  {
    id: "cute",
    name: "Cute Owl",
    emoji: "🦉",
    img: "https://media.base44.com/images/public/6a328f6b6fe1e8d233c220a3/b6b474d1a_generated_image.png",
    tier: "common",
    price: 60,
    glow: "#f9a8d4",
    motion: "bounce",
    dailyCredits: 1,
    discountPct: 5,
    desc: "شكل لطيف بحركة نطّ مرحة.",
    perks: ["كريدت مجاني كل يوم", "خصم 5% على التلخيص", "حركة نطّ حصرية"],
  },
  {
    id: "neon",
    name: "Neon Hero",
    emoji: "🦾",
    img: "https://media.base44.com/images/public/6a328f6b6fe1e8d233c220a3/99a0690d3_generated_image.png",
    tier: "rare",
    price: 150,
    glow: "#22d3ee",
    motion: "pulse",
    model3d: {
      name: "RobotExpressive",
      url: ROBOT_MODEL_URL,
      licenseId: "robot-expressive",
      fitSize: 2.5,
      cameraY: 0.15,
      cameraZ: 5.2,
      tint: "#22d3ee",
      emissiveIntensity: 0.1,
      actions: ROBOT_ACTIONS,
    },
    dailyCredits: 2,
    discountPct: 8,
    desc: "Real 3D neon mascot with GLB actions and a glowing study core.",
    perks: ["2 كريدت كل يوم", "خصم 8% على التلخيص", "مجسم GLB متحرك"],
  },
  {
    id: "warrior",
    name: "Golden Warrior",
    emoji: "⚔️",
    img: "https://media.base44.com/images/public/6a328f6b6fe1e8d233c220a3/a790b23ca_generated_image.png",
    tier: "epic",
    price: 320,
    glow: "#fbbf24",
    motion: "shake",
    dailyCredits: 3,
    discountPct: 12,
    desc: "محارب مدرّع بطاقة أسطورية.",
    perks: ["3 كريدت كل يوم", "خصم 12% على التلخيص", "اهتزاز قوة حصري"],
  },
  {
    id: "demon",
    name: "Inferno Demon",
    emoji: "😈",
    img: "https://media.base44.com/images/public/6a328f6b6fe1e8d233c220a3/6a0320361_generated_image.png",
    tier: "epic",
    price: 450,
    glow: "#ef4444",
    motion: "flame",
    dailyCredits: 4,
    discountPct: 15,
    desc: "شيطان مخيف بلهب وعيون متوهجة.",
    perks: ["4 كريدت كل يوم", "خصم 15% على التلخيص", "لهب ناري حصري"],
  },
  {
    id: "overlord",
    name: "Dark Overlord",
    emoji: "👹",
    img: "https://media.base44.com/images/public/6a328f6b6fe1e8d233c220a3/f388e692d_generated_image.png",
    tier: "legendary",
    price: 750,
    glow: "#a855f7",
    motion: "cosmic",
    dailyCredits: 6,
    discountPct: 20,
    desc: "كيان أسطوري بطاقة كونية مرعبة.",
    perks: ["6 كريدت كل يوم", "خصم 20% على التلخيص", "طاقة كونية حصرية"],
  },
  {
    id: "celestial",
    name: "Celestial Guardian",
    emoji: "👼",
    img: "https://media.base44.com/images/public/6a328f6b6fe1e8d233c220a3/794ec162f_generated_image.png",
    tier: "mythic",
    price: 1200,
    glow: "#fde68a",
    motion: "ascend",
    dailyCredits: 10,
    discountPct: 25,
    desc: "أقوى شكل — كيان سماوي بأجنحة طاقة وهالة إلهية.",
    perks: ["10 كريدت كل يوم", "خصم 25% على التلخيص", "صعود سماوي + أجنحة طاقة"],
  },
  {
    id: "cyber_scholar",
    name: "Cyber Scholar",
    emoji: "⚡",
    img: null,
    gradient: "linear-gradient(135deg,#00e5ff,#0066ff)",
    tier: "rare",
    price: 220,
    glow: "#00d9ff",
    motion: "scan",
    model3d: monsterModel("alien", "Cyber Scholar", MONSTER_BIPED_ACTIONS, {
      fitSize: 2.34,
      cameraY: 0.12,
      cameraZ: 5.05,
    }),
    scale: 1.12,
    dailyCredits: 2,
    discountPct: 8,
    desc: "Real 3D cyber scholar with scan motion and action-ready GLB rig.",
    perks: ["2 كريدت كل يوم", "خصم 8% على التلخيص", "3D scan actions"],
  },
  {
    id: "arcane_scholar",
    name: "Arcane Scholar",
    emoji: "✦",
    img: null,
    gradient: "linear-gradient(135deg,#7c3aed,#ec4899)",
    tier: "epic",
    price: 380,
    glow: "#c850ff",
    motion: "arcane",
    model3d: monsterModel("wizard", "Arcane Scholar", MONSTER_BIPED_ACTIONS, {
      fitSize: 2.3,
      cameraY: 0.14,
      cameraZ: 5.05,
    }),
    scale: 1.12,
    dailyCredits: 3,
    discountPct: 11,
    desc: "بطلة ثلاثية الأبعاد تتحكم في بطاقات المعرفة البلورية.",
    perks: ["3 كريدت كل يوم", "خصم 11% على التلخيص", "مدار بلوري حصري"],
  },
  {
    id: "academy_mech",
    name: "Academy Mech",
    emoji: "◉",
    img: null,
    gradient: "linear-gradient(135deg,#22d3ee,#0ea5e9)",
    tier: "epic",
    price: 500,
    glow: "#22d3ee",
    motion: "mech",
    model3d: monsterModel("dino", "Academy Mech", MONSTER_COMBAT_ACTIONS, {
      fitSize: 2.5,
      cameraY: 0.15,
      cameraZ: 5.15,
      autoRotateSpeed: 0.0031,
    }),
    scale: 1.08,
    dailyCredits: 4,
    discountPct: 13,
    desc: "Real 3D academy mech loaded as GLB with idle, dance and movement actions.",
    perks: ["4 كريدت كل يوم", "خصم 13% على التلخيص", "حركات GLB حقيقية"],
  },
  {
    id: "demon_scholar",
    name: "Inferno Scholar",
    emoji: "▲",
    img: null,
    gradient: "linear-gradient(135deg,#ff3b1f,#ff6a00)",
    tier: "legendary",
    price: 500,
    glow: "#ff3b1f",
    motion: "inferno",
    model3d: monsterModel("demon", "Inferno Scholar", MONSTER_FLYING_ACTIONS, {
      fitSize: 2.62,
      cameraY: 0.08,
      cameraZ: 4.95,
      autoRotateSpeed: 0.003,
    }),
    scale: 1.12,
    dailyCredits: 5,
    discountPct: 17,
    desc: "شيطان أكاديمي ثلاثي الأبعاد بكتاب نار وذيل متوهج.",
    perks: ["5 كريدت كل يوم", "خصم 17% على التلخيص", "لهب جحيمي متحرك"],
  },
];

export const TIER_LABELS = {
  free: { label: "Base", color: "text-muted-foreground", ring: "border-border" },
  common: { label: "Common", color: "text-pink-300", ring: "border-pink-400/40" },
  rare: { label: "Rare", color: "text-cyan-300", ring: "border-cyan-400/40" },
  epic: { label: "Epic", color: "text-amber-300", ring: "border-amber-400/40" },
  legendary: { label: "Legendary", color: "text-purple-300", ring: "border-purple-400/50" },
  mythic: { label: "Mythic", color: "text-yellow-200", ring: "border-yellow-300/50" },
};

export function getSkin(id) {
  return MASCOT_SKINS.find((s) => s.id === id) || MASCOT_SKINS[0];
}

// خصم الشكل المفعّل على تكلفة عملية (يرجّع التكلفة بعد الخصم، حد أدنى 1)
export function applySkinDiscount(cost, skinId) {
  const skin = getSkin(skinId);
  if (!skin.discountPct) return cost;
  const discounted = Math.ceil(cost * (1 - skin.discountPct / 100));
  return Math.max(1, discounted);
}
