import React, { useMemo, useRef, useState } from "react";
import { Check, Download, Printer } from "lucide-react";
import { toast } from "sonner";
import { renderStudyGuideHtml, STUDY_GUIDE_TEMPLATES } from "@/lib/summaryStudyGuide";
import { useLocale } from "@/lib/LocaleContext";
import { cn } from "@/lib/utils";

/**
 * StudyGuideViewer — renders a summary inside one of the HTML study-guide
 * templates.
 *
 * WHY AN IFRAME: the templates are self-contained HTML documents (the owner
 * supplied two of them as files). Rendering the SAME document on screen, in the
 * picker previews and in the downloaded/exported file means what a student picks
 * is exactly what they read and exactly what they export — and it keeps the
 * template CSS from leaking into the app shell.
 *
 * The iframe is sandboxed with no script permission, and the HTML is generated by
 * our own generator (all content escaped), so nothing from a model response can
 * execute here.
 */
export default function StudyGuideViewer({
  document: doc,
  markdown = "",
  title = "",
  templateId,
  onTemplateChange,
  showToolbar = true,
  className = "",
}) {
  const { locale } = useLocale();
  const isEn = locale === "en";
  const frameRef = useRef(null);
  const [internalId, setInternalId] = useState(templateId || STUDY_GUIDE_TEMPLATES[0].id);
  const currentId = templateId || internalId;

  const html = useMemo(
    () => renderStudyGuideHtml({ document: doc, markdown, title, templateId: currentId }),
    [doc, markdown, title, currentId],
  );

  const pick = (id) => {
    setInternalId(id);
    onTemplateChange?.(id);
  };

  const download = () => {
    try {
      const safeTitle = (title || doc?.title?.text || "ملخص").replace(/[\\/:*?"<>|]/g, "-").slice(0, 80);
      const blob = new Blob([html], { type: "text/html;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = window.document.createElement("a");
      link.href = url;
      link.download = `${safeTitle}.html`;
      window.document.body.appendChild(link);
      link.click();
      window.document.body.removeChild(link);
      setTimeout(() => URL.revokeObjectURL(url), 4000);
      toast.success(isEn ? "Study guide downloaded" : "تم تحميل الملف ✅");
    } catch (error) {
      toast.error(error?.message || (isEn ? "Download failed" : "تعذر التحميل"));
    }
  };

  const print = () => {
    try {
      frameRef.current?.contentWindow?.focus();
      frameRef.current?.contentWindow?.print();
    } catch {
      toast.error(isEn ? "Printing is blocked here" : "الطباعة مش متاحة هنا");
    }
  };


  return (
    <div className={cn("space-y-3", className)}>
      {showToolbar && (
        <div className="space-y-2.5 rounded-2xl border border-border bg-[#0E1117] p-3">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <span className="text-[11px] font-black uppercase tracking-[0.16em] text-muted-foreground">
              {isEn ? "Choose a template" : "اختار شكل التلخيص"}
            </span>
            <div className="flex gap-1.5">
              <button
                type="button"
                onClick={download}
                className="inline-flex items-center gap-1.5 rounded-xl bg-primary px-3 py-1.5 text-[11px] font-black text-[#03150c]"
              >
                <Download className="h-3.5 w-3.5" />
                {isEn ? "Download file" : "تحميل الملف"}
              </button>
              <button
                type="button"
                onClick={print}
                className="inline-flex items-center gap-1.5 rounded-xl border border-border px-3 py-1.5 text-[11px] font-bold text-muted-foreground transition-colors hover:text-foreground"
              >
                <Printer className="h-3.5 w-3.5" />
                {isEn ? "Print" : "طباعة"}
              </button>
            </div>
          </div>

          {/* Every card renders the ACTUAL template document — the student sees the
              layout they will get, not a wireframe. */}
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">
            {STUDY_GUIDE_TEMPLATES.map((template) => {
              const selected = currentId === template.id;
              return (
                <button
                  key={template.id}
                  type="button"
                  onClick={() => pick(template.id)}
                  aria-pressed={selected}
                  className={cn(
                    "relative overflow-hidden rounded-xl border text-start transition-colors",
                    selected ? "border-primary ring-1 ring-primary/40" : "border-border hover:border-primary/35",
                  )}
                >
                  <StudyGuidePreview templateId={template.id} className="h-28 w-full" />
                  <span className={cn("block px-2 py-1.5", selected ? "bg-primary/10" : "bg-white/[0.03]")}>
                    <span className={cn("block truncate text-[11px] font-black", selected ? "text-primary" : "text-foreground")}>
                      {isEn ? template.nameEn : template.nameAr}
                    </span>
                    <span className="mt-0.5 block truncate text-[9.5px] text-muted-foreground">
                      {template.descAr}
                    </span>
                  </span>
                  {selected && (
                    <span className="absolute end-1.5 top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-[#03150c]">
                      <Check className="h-2.5 w-2.5" />
                    </span>
                  )}
                </button>
              );
            })}
          </div>
        </div>
      )}

      <iframe
        ref={frameRef}
        title={isEn ? "Study guide" : "ملف المذاكرة"}
        srcDoc={html}
        sandbox=""
        className="w-full rounded-2xl border border-border bg-white"
        style={{ height: "min(78vh, 1100px)" }}
      />
    </div>
  );
}

/** Small, non-interactive preview used by the template picker. */
export function StudyGuidePreview({ templateId, className = "" }) {
  const html = useMemo(
    () => renderStudyGuideHtml({ ...MINI_GUIDE_SAMPLE, templateId }),
    [templateId],
  );
  return (
    <div className={cn("overflow-hidden bg-white", className)} aria-hidden="true">
      <div className="pointer-events-none h-full w-full overflow-hidden">
        <iframe
          title=""
          srcDoc={html}
          sandbox=""
          scrolling="no"
          className="border-0"
          style={{ width: "1180px", height: "1180px", transform: "scale(0.225)", transformOrigin: "top right" }}
        />
      </div>
    </div>
  );
}

/** Fixture the previews render, so a student sees the real design instantly. */
const MINI_GUIDE_SAMPLE = {
  title: "مثال: فسيولوجيا القلب",
  document: {
    title: { text: "مثال: فسيولوجيا القلب" },
    metadata: { sourceRefs: [1, 2, 3, 4] },
    overview: [],
    sections: [
      {
        title: { text: "التوصيل الكهربي للقلب" },
        blocks: [
          { type: "paragraph", role: "definition", content: { text: "العقدة الجيبية هي منظم الإيقاع الطبيعي للقلب بمعدل 60–100 نبضة/دقيقة." } },
          { type: "paragraph", role: "example", content: { text: "تخيل العقدة الجيبية كقائد أوركسترا: هي اللي بتحدد الإيقاع والباقي بيتبعه." } },
          { type: "bullet_list", role: "english_points", items: [{ text: "SA node: primary pacemaker (60–100 bpm)" }, { text: "AV node: delays the impulse to let atria empty" }] },
          { type: "table", role: "body", table: { headers: [{ text: "المصطلح" }, { text: "المعنى" }], rows: [[{ text: "QT interval" }, { text: "زمن الانقباض والارتخاء البطيني" }], [{ text: "Bradycardia" }, { text: "بطء القلب أقل من 60" }]] } },
          { type: "paragraph", role: "warning", content: { text: "فخ الامتحان: بطء القلب مع أعراض (إغماء/هبوط ضغط) = تدخل فوري، ومش مجرد متابعة." } },
          { type: "quote", content: { text: "أي سؤال في المحاضرة الجاية عن العقد الجيبية؟ ركّز على الترتيب والمعدلات." } },
        ],
      },
    ],
    conclusion: [],
  },
};
